### ISSUE TITLE
No module named 'open_clip'

### ISSUE THREAD

**Issue by zhengzetao1** [thecooltechguy/ComfyUI-Stable-Video-Diffusion#41]
# ComfyUI Error Report
## Error Details
- **Node Type:** SVDModelLoader
- **Exception Type:** ModuleNotFoundError
- **Exception Message:** No module named 'open_clip'
## Stack Trace
```
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\nodes.py", line 55, in load_svd_model
    self.svd_model = load_model(
                     ^^^^^^^^^^^

  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\svd.py", line 79, in load_model
    model = instantiate_from_config(config.model).to(device).eval()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\util.py", line 186, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "importlib\__init__.py", line 126, in import_module

  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load

  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 940, in exec_module

  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed

  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\__init__.py", line 1, in <module>
    from .models import AutoencodingEngine, DiffusionEngine

  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\models\__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine

  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\models\autoencoder.py", line 14, in <module>
    from ..modules.autoencoding.regularizers import AbstractRegularizer

  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\modules\__init__.py", line 1, in <module>
    from .encoders.modules import GeneralConditioner

  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\modules\encoders\modules.py", line 8, in <module>
    import open_clip

```
## System Information
- **ComfyUI Version:** v0.2.2
- **Arguments:** ComfyUI\main.py --windows-standalone-build
- **OS:** nt
- **Python Version:** 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
- **Embedded Python:** true
- **PyTorch Version:** 2.4.1+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 4294443008
  - **VRAM Free:** 3451283043
  - **Torch VRAM Total:** 33554432
  - **Torch VRAM Free:** 33554428

## Logs
```
2024-09-29 23:23:28,819 - root - INFO - Total VRAM 4096 MB, total RAM 16022 MB
2024-09-29 23:23:28,820 - root - INFO - pytorch version: 2.4.1+cu124
2024-09-29 23:23:28,820 - root - INFO - Set vram state to: NORMAL_VRAM
2024-09-29 23:23:28,821 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 3050 Laptop GPU : cudaMallocAsync
2024-09-29 23:23:29,647 - root - INFO - Using pytorch cross attention
2024-09-29 23:23:30,761 - root - INFO - [Prompt Server] web root: F:\ComfyUI_windows_portable\ComfyUI\web
2024-09-29 23:23:33,488 - root - WARNING - Skip F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger module for custom nodes due to the lack of NODE_CLASS_MAPPINGS.
2024-09-29 23:23:33,504 - root - INFO - 
Import times for custom nodes:
2024-09-29 23:23:33,504 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
2024-09-29 23:23:33,504 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
2024-09-29 23:23:33,504 - root - INFO -    0.0 seconds (IMPORT FAILED): F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-09-29 23:23:33,504 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-09-29 23:23:33,504 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-09-29 23:23:33,504 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-09-29 23:23:33,505 - root - INFO -    0.0 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
2024-09-29 23:23:33,505 - root - INFO -    0.1 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion
2024-09-29 23:23:33,505 - root - INFO -    0.3 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
2024-09-29 23:23:33,505 - root - INFO -    0.6 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-09-29 23:23:33,505 - root - INFO -    1.3 seconds: F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-09-29 23:23:33,505 - root - INFO - 
2024-09-29 23:23:33,513 - root - INFO - Starting server

2024-09-29 23:23:33,513 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-09-29 23:23:41,299 - root - INFO - got prompt
2024-09-29 23:23:42,219 - root - ERROR - !!! Exception during processing !!! No module named 'open_clip'
2024-09-29 23:23:42,222 - root - ERROR - Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\nodes.py", line 55, in load_svd_model
    self.svd_model = load_model(
                     ^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\svd.py", line 79, in load_model
    model = instantiate_from_config(config.model).to(device).eval()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\util.py", line 186, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\__init__.py", line 1, in <module>
    from .models import AutoencodingEngine, DiffusionEngine
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\models\__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\models\autoencoder.py", line 14, in <module>
    from ..modules.autoencoding.regularizers import AbstractRegularizer
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\modules\__init__.py", line 1, in <module>
    from .encoders.modules import GeneralConditioner
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\modules\encoders\modules.py", line 8, in <module>
    import open_clip
ModuleNotFoundError: No module named 'open_clip'

2024-09-29 23:23:42,223 - root - INFO - Prompt executed in 0.90 seconds
2024-09-29 23:24:27,081 - root - INFO - got prompt
2024-09-29 23:24:27,242 - root - ERROR - !!! Exception during processing !!! No module named 'open_clip'
2024-09-29 23:24:27,244 - root - ERROR - Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 317, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 192, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\nodes.py", line 55, in load_svd_model
    self.svd_model = load_model(
                     ^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\svd.py", line 79, in load_model
    model = instantiate_from_config(config.model).to(device).eval()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\util.py", line 175, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\util.py", line 186, in get_obj_from_str
    return getattr(importlib.import_module(module, package=None), cls)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1126, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\__init__.py", line 1, in <module>
    from .models import AutoencodingEngine, DiffusionEngine
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\models\__init__.py", line 1, in <module>
    from .autoencoder import AutoencodingEngine
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\models\autoencoder.py", line 14, in <module>
    from ..modules.autoencoding.regularizers import AbstractRegularizer
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\modules\__init__.py", line 1, in <module>
    from .encoders.modules import GeneralConditioner
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Stable-Video-Diffusion\libs\sgm\modules\encoders\modules.py", line 8, in <module>
    import open_clip
ModuleNotFoundError: No module named 'open_clip'

2024-09-29 23:24:27,247 - root - INFO - Prompt executed in 0.14 seconds
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":8,"last_link_id":10,"nodes":[{"id":6,"type":"VHS_VideoCombine","pos":{"0":1823,"1":-151},"size":{"0":695.5018310546875,"1":238},"flags":{},"order":5,"mode":0,"inputs":[{"name":"images","type":"IMAGE","link":8,"label":"图像"},{"name":"audio","type":"AUDIO","link":null,"label":"音频"},{"name":"meta_batch","type":"VHS_BatchManager","link":null,"label":"批次管理"},{"name":"vae","type":"VAE","link":null}],"outputs":[{"name":"Filenames","type":"VHS_FILENAMES","links":null,"shape":3,"label":"文件名"}],"properties":{"Node name for S&R":"VHS_VideoCombine"},"widgets_values":{"frame_rate":48,"loop_count":0,"filename_prefix":"AnimateDiff","format":"image/gif","pingpong":false,"save_output":true,"videopreview":{"hidden":false,"paused":false,"params":{"filename":"AnimateDiff_00005.gif","subfolder":"","type":"output","format":"image/gif"}}}},{"id":7,"type":"RIFE VFI","pos":{"0":1322,"1":159},"size":{"0":443.4000244140625,"1":198},"flags":{},"order":4,"mode":0,"inputs":[{"name":"frames","type":"IMAGE","link":7,"label":"图像"},{"name":"optional_interpolation_states","type":"INTERPOLATION_STATES","link":null,"label":"插值规则(可选)"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[8],"slot_index":0,"shape":3,"label":"图像"}],"properties":{"Node name for S&R":"RIFE VFI"},"widgets_values":["rife40.pth",10,8,true,true,1]},{"id":4,"type":"LoadImage","pos":{"0":140,"1":-317},"size":{"0":315,"1":314},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[1],"shape":3,"label":"图像"},{"name":"MASK","type":"MASK","links":null,"shape":3,"label":"遮罩"}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["0 (4).png","image"]},{"id":2,"type":"SVDSampler","pos":{"0":685.015625,"1":-72.78125},"size":{"0":315,"1":198},"flags":{},"order":2,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":1,"slot_index":0,"label":"image"},{"name":"model","type":"MODEL","link":9,"label":"model"}],"outputs":[{"name":"LATENT","type":"LATENT","links":[3],"slot_index":0,"shape":3,"label":"LATENT"}],"properties":{"Node name for S&R":"SVDSampler"},"widgets_values":[127,6,0.02,378,"randomize","cuda"]},{"id":3,"type":"SVDDecoder","pos":{"0":1061,"1":-51},"size":{"0":315,"1":102},"flags":{},"order":3,"mode":0,"inputs":[{"name":"samples_z","type":"LATENT","link":3,"label":"samples_z"},{"name":"model","type":"MODEL","link":10,"label":"model"}],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[7],"slot_index":0,"shape":3,"label":"IMAGE"}],"properties":{"Node name for S&R":"SVDDecoder"},"widgets_values":[14,"cuda"]},{"id":8,"type":"SVDModelLoader","pos":{"0":75,"1":109},"size":{"0":415.8000183105469,"1":130},"flags":{},"order":1,"mode":0,"inputs":[],"outputs":[{"name":"MODEL","type":"MODEL","links":[9,10],"slot_index":0,"shape":3,"label":"MODEL"}],"properties":{"Node name for S&R":"SVDModelLoader"},"widgets_values":["svd.safetensors",14,25,"cuda"]}],"links":[[1,4,0,2,0,"IMAGE"],[3,2,0,3,0,"LATENT"],[7,3,0,7,0,"IMAGE"],[8,7,0,6,0,"IMAGE"],[9,8,0,2,1,"MODEL"],[10,8,0,3,1,"MODEL"]],"groups":[],"config":{},"extra":{"ds":{"scale":0.8390545288824027,"offset":[-9.527758368957414,604.006901026977]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by Jakubelo** [comment]
missing `open_clip_torch` in requirements.

**Comment by HFHL** [comment]
run `pip install open_clip_torch` in terminal.
