### ISSUE TITLE
Went through the install process now it says it installed Torch not compiled with Cuda enabled

### ISSUE THREAD

**Issue by f-rank** [thecooltechguy/ComfyUI-Stable-Video-Diffusion#8]
Throws in console:
** ComfyUI start up time: 2023-11-23 19:35:05.661688

Prestartup times for custom nodes:
   0.0 seconds: D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\main.py", line 72, in <module>
    import execution
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\execution.py", line 12, in <module>
    import nodes
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 20, in <module>
    import comfy.diffusers_load
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\diffusers_load.py", line 4, in <module>
    import comfy.sd
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 114, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
                                  ^^^^^^^^^^^^^^^^^^
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\ComfyUI\comfy\model_management.py", line 83, in get_torch_device
    return torch.device(torch.cuda.current_device())
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 769, in current_device
    _lazy_init()
  File "D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\cuda\__init__.py", line 289, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

D:\WORK\conda_envs\ComfyUI\ComfyUI_windows_portable>pause
Press any key to continue . . .

Any way to mitigate this without a full re-install of Comfy ?

**Comment by Kaz03** [comment]
I'd try to install torch+cu118  with --extra-index-url https://download.pytorch.org/whl/torch

**Comment by JPW0080** [comment]
Same issue occurred on an A1111 Python 3.10.6 ENV

Try This, Obviously change Paths/Torch ver

Command Prompt:
\stable-diffusion-webui\venv\Scripts\activate.bat

pip install https://download.pytorch.org/whl/cu118/torch-2.1.0%2Bcu118-cp310-cp310-win_amd64.whl

**Comment by f-rank** [comment]
I went with :
python_embeded>python.exe -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121

Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121
Requirement already satisfied: torch in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (2.1.0)
Requirement already satisfied: torchvision in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (0.16.0+cu121)
Requirement already satisfied: torchaudio in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (2.1.0+cu121)
Requirement already satisfied: filelock in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.13.1)
Requirement already satisfied: typing-extensions in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (4.8.0)
Requirement already satisfied: sympy in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (1.12)
Requirement already satisfied: networkx in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.2.1)
Requirement already satisfied: jinja2 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.1.2)
Requirement already satisfied: fsspec in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (2023.10.0)
Requirement already satisfied: numpy in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (1.24.4)
Requirement already satisfied: requests in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (2.31.0)
Collecting torch
  Downloading https://download.pytorch.org/whl/cu121/torch-2.1.0%2Bcu121-cp311-cp311-win_amd64.whl (2473.9 MB)
     ---------------------------------------- 2.5/2.5 GB 3.8 MB/s eta 0:00:00
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (9.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch) (2.1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (2023.7.22)
Requirement already satisfied: mpmath>=0.19 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch) (1.3.0)
Installing collected packages: torch
  Attempting uninstall: torch
    Found existing installation: torch 2.1.0
    Uninstalling torch-2.1.0:
      Successfully uninstalled torch-2.1.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
clip-interrogator 0.6.0 requires transformers>=4.27.1, but you have transformers 4.26.1 which is incompatible.
torchdata 0.6.1 requires torch==2.0.1, but you have torch 2.1.0+cu121 which is incompatible.
Successfully installed torch-2.1.0+cu121

It seems to be running again, for now.
For reference this is on  3.11.6, in the python_embeded directory in comfy.
Will try your solutions if run into something later on. Bit finicky with all this.

**Comment by thecooltechguy** [comment]
Hi @f-rank, can you try pulling the latest version of this module and re-installing from the new latest `requirements.txt` file to see if it works? 

I just made some changes to simplify installation & make it work in more environments. thanks!

**Comment by pondloso** [comment]
This happen when i try  re-installing from the new latest requirements.txt
first i install through  manager but it also fail to import node.

**Comment by thecooltechguy** [comment]
@pondloso can you actually try deleting the custom node locally & re-installing it via the ComfyUI Manager?

I just pushed a new update on Github that should make the installation process a lot easier (this time, it won't accidentally re-install any existing pytorch version and it will also auto-download any missing SVD checkpoints into the models folder on startup).

**Comment by thecooltechguy** [comment]
Thanks for sharing @CCpt5 !

Also, I think for low VRAM usage, it would help to reduce the decoding_t parameter in the SVD Decoder node. This controls how many frames are decoded at once.

**Comment by f-rank** [comment]
> Hi @f-rank, can you try pulling the latest version of this module and re-installing from the new latest `requirements.txt` file to see if it works?
> 
> I just made some changes to simplify installation & make it work in more environments. thanks!

On a clean install now, it went through the process ok @thecooltechguy

**Comment by thecooltechguy** [comment]
Awesome, thanks!

**Comment by rachelcenter** [comment]
> I went with : python_embeded>python.exe -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
> 
> Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cu121 Requirement already satisfied: torch in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (2.1.0) Requirement already satisfied: torchvision in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (0.16.0+cu121) Requirement already satisfied: torchaudio in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (2.1.0+cu121) Requirement already satisfied: filelock in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.13.1) Requirement already satisfied: typing-extensions in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (4.8.0) Requirement already satisfied: sympy in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (1.12) Requirement already satisfied: networkx in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.2.1) Requirement already satisfied: jinja2 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (3.1.2) Requirement already satisfied: fsspec in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torch) (2023.10.0) Requirement already satisfied: numpy in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (1.24.4) Requirement already satisfied: requests in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (2.31.0) Collecting torch Downloading https://download.pytorch.org/whl/cu121/torch-2.1.0%2Bcu121-cp311-cp311-win_amd64.whl (2473.9 MB) ---------------------------------------- 2.5/2.5 GB 3.8 MB/s eta 0:00:00 Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from torchvision) (9.5.0) Requirement already satisfied: MarkupSafe>=2.0 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from jinja2->torch) (2.1.3) Requirement already satisfied: charset-normalizer<4,>=2 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.3.2) Requirement already satisfied: idna<4,>=2.5 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (3.4) Requirement already satisfied: urllib3<3,>=1.21.1 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (1.26.18) Requirement already satisfied: certifi>=2017.4.17 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from requests->torchvision) (2023.7.22) Requirement already satisfied: mpmath>=0.19 in d:\work\conda_envs\comfyui\comfyui_windows_portable\python_embeded\lib\site-packages (from sympy->torch) (1.3.0) Installing collected packages: torch Attempting uninstall: torch Found existing installation: torch 2.1.0 Uninstalling torch-2.1.0: Successfully uninstalled torch-2.1.0 ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. clip-interrogator 0.6.0 requires transformers>=4.27.1, but you have transformers 4.26.1 which is incompatible. torchdata 0.6.1 requires torch==2.0.1, but you have torch 2.1.0+cu121 which is incompatible. Successfully installed torch-2.1.0+cu121
> 
> It seems to be running again, for now. For reference this is on 3.11.6, in the python_embeded directory in comfy. Will try your solutions if run into something later on. Bit finicky with all this.

i went to D:\ComfyUI_windows_portable\python_embeded 
then I typed in CMD into the path to bring up terminal
then I typed in python.exe -m pip install torch torchvision torchaudio --extra-index-url https://download.pytorch.org/whl/cu121
and its just sitting there not doing anything. weird!

**Comment by rachelcenter** [comment]
> Hi @f-rank, can you try pulling the latest version of this module and re-installing from the new latest `requirements.txt` file to see if it works?
> 
> I just made some changes to simplify installation & make it work in more environments. thanks!

can you give me detailed instructions on how to do this?

**Comment by rachelcenter** [comment]
> @pondloso can you actually try deleting the custom node locally & re-installing it via the ComfyUI Manager?
> 
> I just pushed a new update on Github that should make the installation process a lot easier (this time, it won't accidentally re-install any existing pytorch version and it will also auto-download any missing SVD checkpoints into the models folder on startup).

i've reinstalled comfyui at least 2 times in the past week for different reasons. please offer me a solution that doesnt involve starting from scratch. its exhausting
